# 命盘维度
DIMENSION_BASIC = '本命'
DIMENSION_RANGE = '大限'
DIMENSION_AGE = '流年'
DIMENSION_LST = [DIMENSION_BASIC, DIMENSION_RANGE, DIMENSION_AGE]

# 天干
SKY = '天干'
SKY_1 = '甲'
SKY_2 = '乙'
SKY_3 = '丙'
SKY_4 = '丁'
SKY_5 = '戊'
SKY_6 = '己'
SKY_7 = '庚'
SKY_8 = '辛'
SKY_9 = '壬'
SKY_10 = '癸'

# 地支
EARTH = '地支'
EARTH_1 = '子'
EARTH_2 = '丑'
EARTH_3 = '寅'
EARTH_4 = '卯'
EARTH_5 = '辰'
EARTH_6 = '巳'
EARTH_7 = '午'
EARTH_8 = '未'
EARTH_9 = '申'
EARTH_10 = '酉'
EARTH_11 = '戌'
EARTH_12 = '亥'

# 十二宫
PALACE_MING = '命宫'
PALACE_FUMU = '父母'
PALACE_FUDE = '福德'
PALACE_TIANZHAI = '田宅'
PALACE_GUANLU = '官禄'
PALACE_PUYI = '仆役'
PALACE_QIANYI = '迁移'
PALACE_JIE = '疾厄'
PALACE_CAIBO = '财帛'
PALACE_ZINV = '子女'
PALACE_FUQI = '夫妻'
PALACE_XIONGDI = '兄弟'
PALACE_LST = [PALACE_MING, PALACE_FUMU, PALACE_FUDE, PALACE_TIANZHAI, PALACE_GUANLU, PALACE_PUYI, PALACE_QIANYI, PALACE_JIE, PALACE_CAIBO, PALACE_ZINV, PALACE_FUQI, PALACE_XIONGDI]

# 四化
HUA_LU = '禄'
HUA_QUAN = '权'
HUA_KE = '科'
HUA_JI = '忌'
HUA_LST = [HUA_LU, HUA_QUAN, HUA_KE, HUA_JI]

# 主星
MAJOR_ZIWEI = '紫微'
MAJOR_TIANJI = '天机'
MAJOR_TAIYANG = '太阳'
MAJOR_WUQU = '武曲'
MAJOR_TIANTONG = '天同'
MAJOR_LIANZHEN = '廉贞'
MAJOR_TIANFU = '天府'
MAJOR_TAIYIN = '太阴'
MAJOR_TANLANG = '贪狼'
MAJOR_JUMEN = '巨门'
MAJOR_TIANXIANG = '天相'
MAJOR_TIANLIANG = '天梁'
MAJOR_QISHA = '七杀'
MAJOR_POJUN = '破军'
MAJOR_LST = [MAJOR_ZIWEI, MAJOR_TIANJI, MAJOR_TAIYANG, MAJOR_WUQU, MAJOR_TIANTONG, MAJOR_LIANZHEN, MAJOR_TIANFU, MAJOR_TAIYIN, MAJOR_TANLANG, MAJOR_JUMEN, MAJOR_TIANXIANG, MAJOR_TIANLIANG, MAJOR_QISHA, MAJOR_POJUN]

# 辅星
MINOR_ZUOFU = '左辅'
MINOR_YOUBI = '右弼'
MINOR_TIANKUI = '天魁'
MINOR_TIANYUE = '天钺'
MINOR_WENCHANG = '文昌'
MINOR_WENQU = '文曲'
MINOR_DIKONG = '地空'
MINOR_DIJIE = '地劫'
MINOR_HUO = '火星'
MINOR_LING = '铃星'
MINOR_TUOLUO = '陀罗'
MINOR_QINGYANG = '擎羊'
MINOR_TIANMA = '天马'
MINOR_LUCUN = '禄存'
MINOR_LST = [MINOR_ZUOFU, MINOR_YOUBI, MINOR_TIANKUI, MINOR_TIANYUE, MINOR_WENCHANG, MINOR_WENQU, MINOR_DIKONG, MINOR_DIJIE, MINOR_HUO, MINOR_LING, MINOR_TUOLUO, MINOR_QINGYANG, MINOR_TIANMA, MINOR_LUCUN]

# 杂曜 
ADJECTIVE_HONGLUAN = '红鸾'
ADJECTIVE_TIANXI = '天喜'
ADJECTIVE_TIANYAO = '天姚'
ADJECTIVE_XIANCHI = '咸池'
ADJECTIVE_GUCHEN = '孤辰'
ADJECTIVE_GUASU = '寡宿'
ADJECTIVE_TIANXING = '天刑'
ADJECTIVE_LONGCHI = '龙池'
ADJECTIVE_FENGGE = '凤阁'
ADJECTIVE_TIANCAI = '天才'
ADJECTIVE_TIANCHU = '天厨'
ADJECTIVE_SANTAI = '三台'
ADJECTIVE_BAZUO = '八座'
ADJECTIVE_ENGUANG = '恩光'
ADJECTIVE_TIANGUI = '天贵'
ADJECTIVE_TIANGUAN = '天官'
ADJECTIVE_TIANKU = '天哭'
ADJECTIVE_TIANXU = '天虚'
ADJECTIVE_POSUI = '破碎'
ADJECTIVE_FEILIAN = '蜚廉'
ADJECTIVE_HUAGAI = '华盖'
ADJECTIVE_YINSHA = '阴煞'
ADJECTIVE_JIESHEN = '解神'
ADJECTIVE_TIANDE = '天德'
ADJECTIVE_YUEDE = '月德'
ADJECTIVE_TIANFU = '天福'
ADJECTIVE_TIANSHOU = '天寿'
ADJECTIVE_TIANSHANG = '天伤'
ADJECTIVE_TIANSHI = '天使'
ADJECTIVE_TIANYUE = '天月'
ADJECTIVE_TIANWU = '天巫'
ADJECTIVE_TAIFU = '台辅'
ADJECTIVE_FENGGAO = '封诰'
ADJECTIVE_TIANKONG = '天空'
ADJECTIVE_XUNKONG = '旬空'
ADJECTIVE_JIEKONG = '截空'
ADJECTIVE_KONGWANG = '空亡'
ADJECTIVE_LST = [ADJECTIVE_HONGLUAN, ADJECTIVE_TIANXI, ADJECTIVE_TIANYAO, ADJECTIVE_XIANCHI, ADJECTIVE_GUCHEN, ADJECTIVE_GUASU, ADJECTIVE_TIANXING, ADJECTIVE_LONGCHI, ADJECTIVE_FENGGE, ADJECTIVE_TIANCAI, ADJECTIVE_TIANCHU, ADJECTIVE_SANTAI, ADJECTIVE_BAZUO, ADJECTIVE_ENGUANG, ADJECTIVE_TIANGUI, ADJECTIVE_TIANGUAN, ADJECTIVE_TIANKU, ADJECTIVE_TIANXU, ADJECTIVE_POSUI, ADJECTIVE_FEILIAN, ADJECTIVE_HUAGAI, ADJECTIVE_YINSHA, ADJECTIVE_JIESHEN, ADJECTIVE_TIANDE, ADJECTIVE_YUEDE, ADJECTIVE_TIANFU, ADJECTIVE_TIANSHOU, ADJECTIVE_TIANSHANG, ADJECTIVE_TIANSHI, ADJECTIVE_TIANYUE, ADJECTIVE_TIANWU, ADJECTIVE_TAIFU, ADJECTIVE_FENGGAO, ADJECTIVE_TIANKONG, ADJECTIVE_XUNKONG, ADJECTIVE_JIEKONG, ADJECTIVE_KONGWANG]

STAR_LST = MAJOR_LST + MINOR_LST + ADJECTIVE_LST

# 天干四化
SKYHUA = {
    SKY_1: {HUA_LU: MAJOR_LIANZHEN, HUA_QUAN: MAJOR_POJUN, HUA_KE: MAJOR_WUQU, HUA_JI: MAJOR_TAIYANG},
    SKY_2: {HUA_LU: MAJOR_TIANJI, HUA_QUAN: MAJOR_TIANLIANG, HUA_KE: MAJOR_ZIWEI, HUA_JI: MAJOR_TAIYIN},
    SKY_3: {HUA_LU: MAJOR_TIANTONG, HUA_QUAN: MAJOR_TIANJI, HUA_KE: MINOR_WENCHANG, HUA_JI: MAJOR_LIANZHEN},
    SKY_4: {HUA_LU: MAJOR_TAIYIN, HUA_QUAN: MAJOR_TIANTONG, HUA_KE: MAJOR_TIANJI, HUA_JI: MAJOR_JUMEN},
    SKY_5: {HUA_LU: MAJOR_TANLANG, HUA_QUAN: MAJOR_TAIYIN, HUA_KE: MINOR_YOUBI, HUA_JI: MAJOR_TIANJI},
    SKY_6: {HUA_LU: MAJOR_WUQU, HUA_QUAN: MAJOR_TANLANG, HUA_KE: MAJOR_TIANLIANG, HUA_JI: MINOR_WENQU},
    SKY_7: {HUA_LU: MAJOR_TAIYANG, HUA_QUAN: MAJOR_WUQU, HUA_KE: MAJOR_TAIYIN, HUA_JI: MAJOR_TIANTONG},
    SKY_8: {HUA_LU: MAJOR_JUMEN, HUA_QUAN: MAJOR_TAIYANG, HUA_KE: MINOR_WENQU, HUA_JI: MINOR_WENCHANG},
    SKY_9: {HUA_LU: MAJOR_TIANLIANG, HUA_QUAN: MAJOR_ZIWEI, HUA_KE: MINOR_ZUOFU, HUA_JI: MAJOR_WUQU},
    SKY_10: {HUA_LU: MAJOR_POJUN, HUA_QUAN: MAJOR_JUMEN, HUA_KE: MAJOR_TAIYIN, HUA_JI: MAJOR_TANLANG}
}
